# Generated by Django 4.2.9 on 2024-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
